# Sample localization file for English. 
# Add more files in this directory for other locales.
# See https://github.com/svenfuchs/rails-i18n/tree/master/rails%2Flocale for starting points.

zh-CN:
  views:
    pagination:
      first: "&laquo; 首页"
      last: "尾页 &raquo;"
      previous: "&lsaquo; 上页"
      next: "下页 &rsaquo;"
      truncate: "..."
  hello: "Hello world"
  app_name: "武汉市新洲一中8104班"
  name: "名称"
  search: "查询"
  placeholder: "输入查询"
  list: "列表"
  index: "列表" 
  slide: "幻灯"   
  empty: "无数据"  
  actions: "操作"
  areas: "Ch_Areas"
  new: "新建"
  show: "显示"
  edit: "修改" 
  copy: "复制"   
  delete: "删除" 
  dft: ""    
  sure: "确定"        
  submit: "提 交"

  description: "描述"  
  type: "类型"
  title: "标题"  
  Date: "日期"   
  location: "地点"  
  active: "激活"
  event: "事件"
  url: "网址"  
  reg_url: "登记网址"   
  article: "文章"  
  content: "内容" 
  news: "新闻" 
  event: "事件"   
  source_site: "来源的网址"  
  introtext: "内容介绍"
  searchable: "可查询" 

  media: "多媒体"  
  gallery: "影集" 
  photo: "照片"
  parent: "父母"
  ancestry: "祖先" 
  widget: "积木" 
  template: "模板"

  page: "页面" 
  user: "用户" 

  sysadm: "系统管理"
  viewadm: "窗口管理"  
  home: "主页"
  menus: "菜单"
  Login: "登陆" 
  Logout: "退出"     
  Sign up: "登记"  

  quit: "Quit"
  join: "Join"
  joined: "Member"
  joining: "Pending"
  Business: " 市场"
  Clothes: "服装"  
  Study: "出国留学"
  House: "房地产"
  Law: "法律"
  IT: "计算机技术"
  Learn: "学习"
  Private: "私人空间"
  Signin: "登录"
  Signup: "登记"
  Communication: "通讯录"
  Home: "首页"
  
  WHXZYZ: "武汉市新洲一中"
  Wuda: "武汉大学"
  AllGroup: "所有用户群"
  AllUser: "所有用户"
  NewGroup: "创建用户群"
# Chinese (China) translations for Devise(3.2.2)
# by Kenrick-Zhou (https://github.com/Kenrick-Zhou)
# https://gist.github.com/Kenrick-Zhou/7909822  
#zh-CN:
  devise:
    confirmations:
      confirmed: "您的帐号已经确认，您现在已登录。"
      send_instructions: "几分钟后，您将收到确认帐号的电子邮件。"
      send_paranoid_instructions: "如果您的邮箱存在于我们的数据库中，您将收到一封确认账号的邮件。"
    failure:
      already_authenticated: "您已经登录。"
      inactive: "您还没有激活帐户。"
      invalid: "邮箱或密码错误。"
      locked: "您的帐号已被锁定。"
      last_attempt: "您还有最后一次尝试机会，再次失败您的账号将被锁定。"
      not_found_in_database: "邮箱或密码错误。"
      timeout: "您已登录超时，请重新登录。"
      unauthenticated: "继续操作前请注册或者登录。"
      unconfirmed: "继续操作前请先确认您的帐号。"
    mailer:
      confirmation_instructions:
        subject: "确认信息"
      reset_password_instructions:
        subject: "重置密码信息"
      unlock_instructions:
        subject: "解锁信息"
    omniauth_callbacks:
      failure: "因为%{reason}，所以您无法从%{kind}获得授权。"
      success: "成功地从%{kind}获得授权。"
    passwords:
      no_token: "这是密码重置页面，未重置邮件不得访问此页面。如果您是通过重置邮件而来的，请确保您访问的URL是完整的。"
      send_instructions: "几分钟后，您将收到重置密码的电子邮件。"
      send_paranoid_instructions: "如果您的邮箱存在于我们的数据库中，您将收到一封找回密码的邮件。"
      updated: "您的密码已修改成功，您现在已登录。"
      updated_not_active: "您的密码已修改成功。"
    registrations:
      destroyed: "再见！您的帐户已成功注销。我们希望很快可以再见到您。"
      signed_up: "欢迎您！您已注册成功。"
      signed_up_but_inactive: "您已注册，但尚未激活账号。"
      signed_up_but_locked: "您已注册，但账号被锁定了。"
      signed_up_but_unconfirmed: "一封带有确认链接的邮件已经发送至您的邮箱，请检查邮箱（包括垃圾邮箱），并点击该链接激活您的账号。"
      update_needs_confirmation: "信息更新成功，但我们需要染整您的新电子邮件地址，请检查邮箱（包括垃圾邮箱），并点击该链接激活您的账号。"
      updated: "帐号资料更新成功。"
    sessions:
      signed_in: "登录成功."
      signed_out: "退出成功."
    unlocks:
      send_instructions: "几分钟后，您将收到一封解锁帐号的邮件。"
      send_paranoid_instructions: "如果您的邮箱存在于我们的数据库中，您将收到一封解锁账号的邮件。"
      unlocked: "您的帐号已成功解锁，您现在已登录。"
  errors:
    messages:
      already_confirmed: "已经确认，请重新登录。"
      confirmation_period_expired: "请在%{period}内确认注册, 请重新注册。"
      expired: "邮件确认已过期，请重新注册。"
      not_found: "没有找到。"
      not_locked: "未锁定。"
      not_saved:
        one: "因为1个错误导致此%{resource}保存失败:"
        other: "因为%{count}个错误导致此%{resource}保存失败:"  
